// quiet: true — 그렇지 않으면 dotenv가 stdout에 안내 문구를 찍는데,
// 이게 scripts/build-prompt.js의 출력 리다이렉트에 섞여 AI 프롬프트를 오염시킨 적이 있다.
require("dotenv").config({ quiet: true });

const COUNTRY = (process.env.COUNTRY || "KR").toUpperCase();

const COUNTRIES = {
  KR: {
    code: "KR",
    lang: "ko",
    trendsGeo: "KR",
    newsHl: "ko",
    newsGl: "KR",
    newsCeid: "KR:ko",
    promptLanguage: "한국어",
    categories: ["IT/과학", "경제", "스포츠", "엔터", "사회/환경"],
    noArticleText: "관련 기사를 찾을 수 없어요",
    numberFormat: { style: "myriad", units: { man: "만", cheon: "천" } },
    ui: {
      pageTitle: "NOW in Korea · 실시간 인기 검색어",
      logoSuffix: "in Korea",
      heading2: "가장 인기 있는 키워드를 모아봤어요",
      searchPlaceholder: "궁금한 키워드를 검색해보세요 (Enter로 구글 검색)",
      updatedPrefix: "KST",
      updatedSuffix: "업데이트",
      countdownSuffix: "뒤에 다시 확인해요",
      footer: "Google Trends(대한민국) 공식 RSS 피드(Daily Search Trends) 기반 · 네이버 실검이 아니며 구글과 제휴 관계가 없습니다",
      newBadge: "NEW",
      aiTag: "AI 요약",
      loadErrorPrefix: "데이터를 불러오지 못했습니다",
      timeZone: "Asia/Seoul",
      locale: "ko-KR",
    },
  },
  JP: {
    code: "JP",
    lang: "ja",
    trendsGeo: "JP",
    newsHl: "ja",
    newsGl: "JP",
    newsCeid: "JP:ja",
    promptLanguage: "日本語",
    categories: ["IT・科学", "経済", "スポーツ", "エンタメ", "社会・環境"],
    noArticleText: "関連記事が見つかりません",
    numberFormat: { style: "myriad", units: { man: "万", cheon: "千" } },
    ui: {
      pageTitle: "NOW in Japan · リアルタイム急上昇ワード",
      logoSuffix: "in Japan",
      heading2: "人気のキーワードを集めました",
      searchPlaceholder: "気になるキーワードを検索 (Enterでgoogle検索)",
      updatedPrefix: "JST",
      updatedSuffix: "更新",
      countdownSuffix: "後に更新されます",
      footer: "Google Trends（日本）公式RSSフィード（Daily Search Trends）基準 · Googleとの提携関係はありません",
      newBadge: "NEW",
      aiTag: "AI要約",
      loadErrorPrefix: "データを読み込めませんでした",
      timeZone: "Asia/Tokyo",
      locale: "ja-JP",
    },
  },
  US: {
    code: "US",
    lang: "en",
    trendsGeo: "US",
    newsHl: "en-US",
    newsGl: "US",
    newsCeid: "US:en",
    promptLanguage: "English",
    categories: ["Tech/Science", "Business", "Sports", "Entertainment", "Society/Environment"],
    noArticleText: "No related article found",
    numberFormat: { style: "thousand", units: { million: "M", thousand: "K" } },
    ui: {
      pageTitle: "NOW in the US · Trending Searches",
      logoSuffix: "in the US",
      heading2: "The most popular keywords, all in one place",
      searchPlaceholder: "Search for a keyword (Enter to search Google)",
      updatedPrefix: "ET",
      updatedSuffix: "updated",
      countdownSuffix: "until the next update",
      footer: "Based on the official Google Trends (United States) RSS feed (Daily Search Trends) · Not affiliated with Google",
      newBadge: "NEW",
      aiTag: "AI Summary",
      loadErrorPrefix: "Failed to load data",
      timeZone: "America/New_York",
      locale: "en-US",
    },
  },
  GB: {
    code: "GB",
    lang: "en",
    trendsGeo: "GB",
    newsHl: "en-GB",
    newsGl: "GB",
    newsCeid: "GB:en",
    promptLanguage: "English",
    categories: ["Tech/Science", "Business", "Sports", "Entertainment", "Society/Environment"],
    noArticleText: "No related article found",
    numberFormat: { style: "thousand", units: { million: "M", thousand: "K" } },
    ui: {
      pageTitle: "NOW in the UK · Trending Searches",
      logoSuffix: "in the UK",
      heading2: "The most popular keywords, all in one place",
      searchPlaceholder: "Search for a keyword (Enter to search Google)",
      updatedPrefix: "UK",
      updatedSuffix: "updated",
      countdownSuffix: "until the next update",
      footer: "Based on the official Google Trends (United Kingdom) RSS feed (Daily Search Trends) · Not affiliated with Google",
      newBadge: "NEW",
      aiTag: "AI Summary",
      loadErrorPrefix: "Failed to load data",
      timeZone: "Europe/London",
      locale: "en-GB",
    },
  },
  DE: {
    code: "DE",
    lang: "de",
    trendsGeo: "DE",
    newsHl: "de",
    newsGl: "DE",
    newsCeid: "DE:de",
    promptLanguage: "Deutsch",
    categories: ["Technik/Wissenschaft", "Wirtschaft", "Sport", "Unterhaltung", "Gesellschaft/Umwelt"],
    noArticleText: "Kein zugehöriger Artikel gefunden",
    numberFormat: { style: "thousand", units: { million: "Mio.", thousand: "Tsd." } },
    ui: {
      pageTitle: "NOW in Germany · Aktuelle Trend-Suchbegriffe",
      logoSuffix: "in Germany",
      heading2: "Die beliebtesten Keywords, gesammelt für dich",
      searchPlaceholder: "Nach einem Keyword suchen (Enter für Google-Suche)",
      updatedPrefix: "CET",
      updatedSuffix: "aktualisiert",
      countdownSuffix: "bis zur nächsten Aktualisierung",
      footer: "Basierend auf dem offiziellen Google Trends (Deutschland) RSS-Feed (Daily Search Trends) · Keine Partnerschaft mit Google",
      newBadge: "NEW",
      aiTag: "KI-Zusammenfassung",
      loadErrorPrefix: "Daten konnten nicht geladen werden",
      timeZone: "Europe/Berlin",
      locale: "de-DE",
    },
  },
};

const CURRENT = COUNTRIES[COUNTRY] || COUNTRIES.KR;

module.exports = { COUNTRY, COUNTRIES, CURRENT };
